name: tcc compiler
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cmd.exe /c build.bat & dir
      
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Releases
        path: |
          *.exe
          *.dll
          !tcc*.exe
          !tcc*.dll

              
